sudo: false
language: java
install:
 - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
script: 
  - mvn test -B
  - node_modules/.bin/newman run pruebas/PruebasLogin.postman_collection.json -e pruebas/tests.postman_environment.json
 
deploy:
  provider: heroku
  api_key:
    secure: GFj4GzFLqmJUwvcZZcyRQY05vRGIyqy5ielJWfk1q3/mf3XRxqeoh5x10uTCnTA+eJ5tN/1LxYqE3+NJqCk6NaiA+jESJfzwtS2gI54cP0dmsCSMW5oxhNIZKIZVnrDySbhE0tnqJLG6QCIMwDUtWgQdtYJPSNxhbZ3Cam81l1+7YTN/sBJes524IYK2dXO8oVnHzDRNRPMZMuSLkuTea0TK4oZp5y+4V6jOu88nhzzeA7acqerfS9a791tkG4wXr+06oSJaN35SD+JgC4QkAD7uVro29WDfewQuFkml9QUhNAFPw3TeVOCRGO2puMvrSVVc89/ANk2clkGoy2I94njOAwLB7SABn7JP0alYVWmQlcs0nyEpMm8/efQ5HF4Yayorgt7shhPC8jY6Ey0X9uDHpFi6RWB6K7SQO27Q3SWJ7pBldxnyoBzsw9e+mMyqEvJSNTSnmV9C5KFhNp7bzRA1nFjfC760JhdfcYX2R6dHDcFygRLi6MBnSfaeM3MNcvc0MkIzkrqWE9NZNjtIt+mbczU8uGbkXf5EWgaLVXnlmD4B16OBJLdv0bJ1+s1KxPbFLP9HdYN/1NmU1ftD8h3fXBg4Lh/UQH5bdKRAq1htV4/5e2KFNqaqKn3jW7yl+jkLDRpyz6IVt0fT3v/OwDLONbpY37sOQrcE760NUOg=
  app: avengerslive
  on:
    repo: RubenPerez95/AvengersLive
notifications:
  slack: e3-avengerslive:uzLr8FFBLr3hOUnrBLNto2I6
services: mongodb